import {CardMap} from './types'

export default {
	'1': {color: 'red', type: 'seven'},
	'2': {color: 'green', type: 'seven'},
	'3': {color: 'ball', type: 'seven'},
	'4': {color: 'acorn', type: 'seven'},
	'5': {color: 'red', type: 'eight'},
	'6': {color: 'green', type: 'eight'},
	'7': {color: 'ball', type: 'eight'},
	'8': {color: 'acorn', type: 'eight'},
	'9': {color: 'red', type: 'nine'},
	'10': {color: 'green', type: 'nine'},
	'11': {color: 'ball', type: 'nine'},
	'12': {color: 'acorn', type: 'nine'},
	'13': {color: 'red', type: 'ten'},
	'14': {color: 'green', type: 'ten'},
	'15': {color: 'ball', type: 'ten'},
	'16': {color: 'acorn', type: 'ten'},
	'17': {color: 'red', type: 'jack'},
	'18': {color: 'green', type: 'jack'},
	'19': {color: 'ball', type: 'jack'},
	'20': {color: 'acorn', type: 'jack'},
	'21': {color: 'red', type: 'miner'},
	'22': {color: 'green', type: 'miner'},
	'23': {color: 'ball', type: 'miner'},
	'24': {color: 'acorn', type: 'miner'},
	'25': {color: 'red', type: 'king'},
	'26': {color: 'green', type: 'king'},
	'27': {color: 'ball', type: 'king'},
	'28': {color: 'acorn', type: 'king'},
	'29': {color: 'red', type: 'ace'},
	'30': {color: 'green', type: 'ace'},
	'31': {color: 'ball', type: 'ace'},
	'32': {color: 'acorn', type: 'ace'}
} as CardMap
